"""init

Revision ID: 8005c7c6faf6
Revises: 
Create Date: 2026-09-01 23:12:12.644025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8005c7c6faf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_groups_name'))
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('name', name=op.f('uq_rooms_name'))
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('name', name=op.f('uq_subjects_name'))
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teachers')),
    sa.UniqueConstraint('name', name=op.f('uq_teachers_name'))
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_type', sa.Enum('COLLEGE', 'UNIVERSITY', name='grouptype'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('subgroup', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('week_type', sa.Enum('EVERY', 'ODD', 'EVEN', name='weektype'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_schedule_group_id_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_schedule_room_id_rooms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_schedule_subject_id_subjects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_schedule_teacher_id_teachers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule')),
    sa.UniqueConstraint('group_id', 'subgroup', 'teacher_id', 'week_type', 'day_of_week', 'lesson_number', name='uq_schedule_entry')
    )
    op.create_index(op.f('ix_schedule_group_id'), 'schedule', ['group_id'], unique=False)
    op.create_index(op.f('ix_schedule_room_id'), 'schedule', ['room_id'], unique=False)
    op.create_index(op.f('ix_schedule_subject_id'), 'schedule', ['subject_id'], unique=False)
    op.create_index(op.f('ix_schedule_teacher_id'), 'schedule', ['teacher_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('TELEGRAM', 'VK', name='platform', native_enum=False), nullable=False),
    sa.Column('platform_user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('tg_topic_id', sa.Integer(), nullable=True),
    sa.Column('tg_tracking', sa.Boolean(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('bot_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('default_group_id', sa.Integer(), nullable=True),
    sa.Column('default_teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_group_id'], ['groups.id'], name=op.f('fk_users_default_group_id_groups')),
    sa.ForeignKeyConstraint(['default_teacher_id'], ['teachers.id'], name=op.f('fk_users_default_teacher_id_teachers')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_users_group_id_groups')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_users_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('platform', 'platform_user_id', name='uq_users_platform_platform_user_id')
    )
    op.create_index(op.f('ix_users_platform_user_id'), 'users', ['platform_user_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('START', 'SCHEDULE_VIEW', 'DAY_VIEW', 'TODAY_VIEW', 'DEFAULT_TEACHER_SELECTED', 'DEFAULT_GROUP_SELECTED', name='activitytype'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_activities_group_id_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_activities_room_id_rooms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_activities_teacher_id_teachers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index(op.f('ix_activities_action'), 'activities', ['action'], unique=False)
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_group_id'), 'activities', ['group_id'], unique=False)
    op.create_index(op.f('ix_activities_room_id'), 'activities', ['room_id'], unique=False)
    op.create_index(op.f('ix_activities_teacher_id'), 'activities', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_teacher_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_room_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_group_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_action'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_platform_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schedule_teacher_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_subject_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_room_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_group_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('rooms')
    op.drop_table('groups')
    # ### end Alembic commands ###
