name: Deploy schedule

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/schedule:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/schedule:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy on server via SSH
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/schedule:latest
            docker stop schedule || true
            docker rm schedule || true
          
            mkdir -p /root/schedule
          
            docker run -d --name schedule \
              --restart=always \
              -v /root/schedule/config.toml:/schedule/config.toml \
              -v /root/schedule:/schedule/data \
              ${{ secrets.DOCKER_USERNAME }}/schedule:latest
          EOF
