name: Deploy schedule

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Code linting
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.13.0
          args: check
          src: "."

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff
        run: ruff check .

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: List files in current directory
        run: ls -la

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/schedule:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/schedule:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy on server via SSH
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/schedule:latest
            docker stop schedule || true
            docker rm schedule || true
          
            mkdir -p /root/schedule
          
            docker run -d --name schedule \
              --restart=always \
              -v /root/schedule/config.toml:/schedule/config.toml \
              -v /root/schedule:/schedule/data \
              ${{ secrets.DOCKER_USERNAME }}/schedule:latest
          EOF
